### DISCUSSION TITLE
Unable to run Android tests in Github actions. (It keeps me saying the UiAutomator2 is not installed, but it is)

### DISCUSSION THREAD

**Discussion by tamaniniandre** [webdriverio/webdriverio#13891] [Q&A]
Hello all!

I have been trying to run my tests in the GitHub actions in an Android device, it seems I have everything configured, but when I will run the tests I've been getting the error:

> webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)

The execution fails exactly at the point:

    - name: Run tests
      run: yarn test-mobile-android -- "@EVENTS"

The Appium seems to be installed and ready:

![image](https://github.com/user-attachments/assets/a5f5a7b2-870e-44d8-9817-b8729fbe2543)

My GitHub Actions file:

```
name: tyb-tests-mobile

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - apiLevel: 32
          emuTag: google_apis
          arch: x86_64

    env:
      CI: true
      ANDROID_AVD: emulator
      ENV_TYB: DEMO
      SLACK_WEBHOOK: ${{ secrets.SLACK_STAGE_WEBHOOK }}
      GIT_HUB: true
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 22.5.1

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.apiLevel }}
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        avd-name: ${{ env.ANDROID_AVD }}
        force-avd-creation: false
        api-level: ${{ matrix.apiLevel }}
        disable-spellchecker: true
        target: ${{ matrix.emuTag }}
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        arch: ${{ matrix.arch }}
        disable-animations: true
        script: echo "Generated AVD snapshot for caching."

    - uses: reactivecircus/android-emulator-runner@v2
      name: e2e_api${{ matrix.apiLevel }}
      with:
        script: echo "Mobile is ready"
        avd-name: ${{ env.ANDROID_AVD }}
        force-avd-creation: false
        api-level: ${{ matrix.apiLevel }}
        disable-spellchecker: true
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        target: ${{ matrix.emuTag }}
        arch: ${{ matrix.arch }}
    
    - run: |
        #!/bin/bash
        set -ex
        npm install -g appium
        appium -v
        appium &>/dev/null &
        appium driver install uiautomator2
        appium driver doctor uiautomator2
        appium driver list --installed 
        yarn install
      name: Start automation

    - name: Run tests
      run: yarn test-mobile-android -- "@EVENTS"

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-report-result
        path: mobile-automation/evidences/allure-results

```

My capabilities:
 
```
//@ts-nocheck

import { config as config } from './wdio.shared.conf.js';

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {   "wdio:maxInstances": 2,
        "appium:platformName": "Android",
        "appium:automationName": "UiAutomator2",
        "appium:avd": "emulator",
        'appium:app': `${process.cwd()}/app/android/app-release.apk`,
        "appium:newCommandTimeout": 0,
        "appium:useNativeCachingStrategy": true,
        "appium:noReset": true,
        "appium:disableIdLocatorAutocompletion": true,
       excludeDriverLogs: ['*']// '*' to exclude all logs
      },
];

const _config = config;
export { _config as config };

import LoginActions from "./step-definitions/pageobjects/actions/login.actions.js";

export let executed: string;

export const config: WebdriverIO.Config = {
    // ====================
    // Runner and framework
    // Configuration
    // ====================
    autoCompileOpts: {
        autoCompile: true,
        // see https://github.com/TypeStrong/ts-node#cli-and-programmatic-options
        // for all available options
        tsNodeOpts: {
            transpileOnly: true,
            project: '../tsconfig.json'
        }
    },
    capabilities: [],
    runner: 'local',
    framework: 'cucumber',
    outputDir: "./evidences/allure-results",
    waitforTimeout: 80000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    specs: ['./features/*/*feature'],
    cucumberOpts: {
        retry: 1,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        strict: true,
        timeout: 500000,
        ignoreUndefinedDefinitions: false,
        require: [
            './step-definitions/*/*.ts',
            './step-definitions/*/**/*.ts',
            './step-definitions/*/*/*.ts',
            './step-definitions/*.ts',
            './../tyb-qa-resources/utils/*.ts',
            '../api-automation/steps-definitions/*/*/*.ts',
            '../api-automation/steps-definitions/*/*.ts',
            './../api-automation/*/*.ts',
        ],
        import: [
            './step-definitions/*/*.ts',
            './step-definitions/*/**/*.ts',
            './step-definitions/*/*/*.ts',
            './step-definitions/*.ts',
            './../tyb-qa-resources/utils/*.ts',
            '../api-automation/steps-definitions/*/*/*.ts',
            '../api-automation/steps-definitions/*/*.ts',
            './../api-automation/*/*.ts',
        ],
        requireModule: ['ts-node/register'],
    },
    maxInstances: 1,
    // ====================
    // Appium Configuration
    // ====================
    reporters: [
        'dot',
        [ 'allure', {
            outputDir: './evidences/allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
            useCucumberStepReporter: true
            
        }],
        'cucumberjs-json',
    ],
    services: [
        ['appium', {
            logPath: './test-report/'
        }
        ],
    ],
};

```

Full log error:

```
2024-11-18T19:42:06.335Z INFO @wdio/local-runner: Run worker command: run
2024-11-18T19:42:07.025Z INFO webdriver: Initiate new session using the WebDriver protocol
2024-11-18T19:42:07.025Z INFO @wdio/utils: Connecting to existing driver at http://127.0.0.1:39565/
2024-11-18T19:42:07.105Z INFO webdriver: [POST] http://127.0.0.1:39565/session
2024-11-18T19:42:07.105Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'wdio:maxInstances': 2,
      'appium:platformName': 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:avd': 'emulator',
      'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
      'appium:newCommandTimeout': 0,
      'appium:useNativeCachingStrategy': true,
      'appium:noReset': true,
      'appium:disableIdLocatorAutocompletion': true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'wdio:maxInstances': 2,
    'appium:platformName': 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:avd': 'emulator',
    'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
    'appium:newCommandTimeout': 0,
    'appium:useNativeCachingStrategy': true,
    'appium:noReset': true,
    'appium:disableIdLocatorAutocompletion': true
  }
}
2024-11-18T19:42:07.473Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
2024-11-18T19:42:07.474Z INFO webdriver: Retrying 1/3
2024-11-18T19:42:07.474Z INFO webdriver: [POST] http://127.0.0.1:39565/session
2024-11-18T19:42:07.474Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'wdio:maxInstances': 2,
      'appium:platformName': 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:avd': 'emulator',
      'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
      'appium:newCommandTimeout': 0,
      'appium:useNativeCachingStrategy': true,
      'appium:noReset': true,
      'appium:disableIdLocatorAutocompletion': true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'wdio:maxInstances': 2,
    'appium:platformName': 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:avd': 'emulator',
    'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
    'appium:newCommandTimeout': 0,
    'appium:useNativeCachingStrategy': true,
    'appium:noReset': true,
    'appium:disableIdLocatorAutocompletion': true
  }
}
2024-11-18T19:42:07.798Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
2024-11-18T19:42:07.798Z INFO webdriver: Retrying 2/3
2024-11-18T19:42:07.798Z INFO webdriver: [POST] http://127.0.0.1:39565/session
2024-11-18T19:42:07.798Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'wdio:maxInstances': 2,
      'appium:platformName': 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:avd': 'emulator',
      'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
      'appium:newCommandTimeout': 0,
      'appium:useNativeCachingStrategy': true,
      'appium:noReset': true,
      'appium:disableIdLocatorAutocompletion': true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'wdio:maxInstances': 2,
    'appium:platformName': 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:avd': 'emulator',
    'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
    'appium:newCommandTimeout': 0,
    'appium:useNativeCachingStrategy': true,
    'appium:noReset': true,
    'appium:disableIdLocatorAutocompletion': true
  }
}
2024-11-18T19:42:08.123Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
2024-11-18T19:42:08.123Z INFO webdriver: Retrying 3/3
2024-11-18T19:42:08.123Z INFO webdriver: [POST] http://127.0.0.1:39565/session
2024-11-18T19:42:08.123Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'wdio:maxInstances': 2,
      'appium:platformName': 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:avd': 'emulator',
      'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
      'appium:newCommandTimeout': 0,
      'appium:useNativeCachingStrategy': true,
      'appium:noReset': true,
      'appium:disableIdLocatorAutocompletion': true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'wdio:maxInstances': 2,
    'appium:platformName': 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:avd': 'emulator',
    'appium:app': '/home/runner/work/tyb-qa/tyb-qa/mobile-automation/app/android/app-release.apk',
    'appium:newCommandTimeout': 0,
    'appium:useNativeCachingStrategy': true,
    'appium:noReset': true,
    'appium:disableIdLocatorAutocompletion': true
  }
}
2024-11-18T19:42:08.443Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
2024-11-18T19:42:08.443Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
    at getErrorFromResponseBody (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/utils.js:195:12)
    at NodeJSRequest._request (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/request/index.js:193:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startWebDriverSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/utils.js:64:20)
    at async Function.newSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/index.js:19:45)
    at async remote (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriverio/build/index.js:46:22)
    at async Runner._startSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:241:29)
    at async Runner._initSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:207:25)
    at async Runner.run (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:88:19)
2024-11-18T19:42:08.444Z ERROR @wdio/runner: Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
    at startWebDriverSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/utils.js:69:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.newSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriver/build/index.js:19:45)
    at async remote (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/webdriverio/build/index.js:46:22)
    at async Runner._startSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:241:29)
    at async Runner._initSession (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:207:25)
    at async Runner.run (file:///home/runner/work/tyb-qa/tyb-qa/node_modules/@wdio/runner/build/index.js:88:19)

```
