### DISCUSSION TITLE
Gitlab pipeline setup and Selenium Standalone service

### DISCUSSION THREAD

**Discussion by alex-vitry** [webdriverio/webdriverio#7232] [Q&A]
Hi,

I'm setting up basic test execution pipeline in Gitlab using `selenium-standalone` service, and I'm facing an issue with download of selenium-server.jar and drivers:

```
Error in "getDownloadStream". Could not download https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
See more details below:
Timeout awaiting 'request' for 90000ms
```

The driver and selenium server url are reachable in my Gitlab runner, and files can be downloaded with curl.

wdio.conf.js:
```
services: [['selenium-standalone', { drivers: { firefox: '0.29.1', chrome: true, chromiumedge: 'latest' } }]],
capabilities: [{maxInstances: 5, browserName: 'chrome','goog:chromeOptions': {...}}]
```
gitlab-ci.yml:
```
image: smartqe/wdio:latest
e2e:chrome:
  stage: test
  script:
    - npm install
    - npm run test:chrome:uat (wdio script)
```

`"@wdio/cli": "^7.9.0"`

Anyone has encountered this before?
