### ISSUE TITLE
[🐛 Bug]: ERROR webdriver: Could not connect to Bidi protocol in docker CI setup

### ISSUE THREAD

**Issue by alcpereira** [webdriverio/webdriverio#14389]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.12.2

### Node.js Version

20.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      browserName: "chrome",
      acceptInsecureCerts: true,

      "goog:chromeOptions": {
        args: ["--headless"],
        mobileEmulation: {
          deviceName: "iPhone 6",
        },
      },
    }
```

### What happened?

I am using WebdriverIO and Docker in the same Github Runner using the following docker compose:

```yaml
version: "3.6"
services:
  selenium-hub:
    image: selenium/hub:4.14.1
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    logging:
      driver: "none"

  chrome:
    image: selenium/node-chrome:117.0-20230920
    shm_size: 4gb
    deploy:
      replicas: 4
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=8
      - START_XVFB=false
```

We are getting those errors starting after the bump from version `9.10.1` to `9.12.2`

### What is your expected behavior?

No errors in the logs, I also suspect there is a delay because of wdio trying to connect via BiDi

### How to reproduce the bug.

Regular wdio run using official Docker images in CI
(Let me know if you want me to create a reproduction repo)

### Relevant log output

```typescript
As you can see wdio tries to connect to random WebSocket ports.

[0-15] 2025-04-08T13:56:11.691Z ERROR webdriver: Could not connect to Bidi protocol
[0-15]   - connect ECONNREFUSED 127.0.0.1:12632
[0-3] 2025-04-08T13:56:11.715Z ERROR webdriver: Could not connect to Bidi protocol
[0-3]   - connect ECONNREFUSED 127.0.0.1:17007
[0-18] 2025-04-08T13:56:11.765Z ERROR webdriver: Could not connect to Bidi protocol
[0-18]   - connect ECONNREFUSED 127.0.0.1:7158
[0-11] 2025-04-08T13:56:11.781Z ERROR webdriver: Could not connect to Bidi protocol
[0-11]   - connect ECONNREFUSED 127.0.0.1:23073
[0-4] 2025-04-08T13:56:11.868Z ERROR webdriver: Could not connect to Bidi protocol
[0-4]   - connect ECONNREFUSED 127.0.0.1:14392
[0-12] 2025-04-08T13:56:11.885Z ERROR webdriver: Could not connect to Bidi protocol
[0-12]   - connect ECONNREFUSED 127.0.0.1:28424
[0-2] 2025-04-08T13:56:11.891Z ERROR webdriver: Could not connect to Bidi protocol
[0-2]   - connect ECONNREFUSED 127.0.0.1:2524
[0-9] 2025-04-08T13:56:11.904Z ERROR webdriver: Could not connect to Bidi protocol
[0-9]   - connect ECONNREFUSED 127.0.0.1:18310
[0-14] 2025-04-08T13:56:11.915Z ERROR webdriver: Could not connect to Bidi protocol
[0-14]   - connect ECONNREFUSED 127.0.0.1:2241
[0-19] 2025-04-08T13:56:11.939Z ERROR webdriver: Could not connect to Bidi protocol
[0-19]   - connect ECONNREFUSED 127.0.0.1:10899
[0-5] 2025-04-08T13:56:11.968Z ERROR webdriver: Could not connect to Bidi protocol
[0-5]   - connect ECONNREFUSED 127.0.0.1:5052
[0-10] 2025-04-08T13:56:11.987Z ERROR webdriver: Could not connect to Bidi protocol
[0-10]   - connect ECONNREFUSED 127.0.0.1:26544
[0-6] 2025-04-08T13:56:11.987Z ERROR webdriver: Could not connect to Bidi protocol
[0-6]   - connect ECONNREFUSED 127.0.0.1:17721
[0-13] 2025-04-08T13:56:12.023Z ERROR webdriver: Could not connect to Bidi protocol
[0-13]   - connect ECONNREFUSED 127.0.0.1:24614
[0-8] 2025-04-08T13:56:12.141Z ERROR webdriver: Could not connect to Bidi protocol
[0-8]   - connect ECONNREFUSED 127.0.0.1:5812
[0-0] 2025-04-08T13:56:12.192Z ERROR webdriver: Could not connect to Bidi protocol
[0-0]   - connect ECONNREFUSED 127.0.0.1:18133
[0-17] 2025-04-08T13:56:12.201Z ERROR webdriver: Could not connect to Bidi protocol
[0-17]   - connect ECONNREFUSED 127.0.0.1:26140
[0-16] 2025-04-08T13:56:12.217Z ERROR webdriver: Could not connect to Bidi protocol
[0-16]   - connect ECONNREFUSED 127.0.0.1:6700
[0-7] 2025-04-08T13:56:12.239Z ERROR webdriver: Could not connect to Bidi protocol
[0-7]   - connect ECONNREFUSED 127.0.0.1:2331
[0-1] 2025-04-08T13:56:12.263Z ERROR webdriver: Could not connect to Bidi protocol
[0-1]   - connect ECONNREFUSED 127.0.0.1:16347
[0-15] 2025-04-08T13:56:21.689Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:12632/session/a569c651a0b81311043212eb4cba44c2"
[0-3] 2025-04-08T13:56:21.713Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:17007/session/224b581ead644e81a1126e684fb6e2ab"
[0-18] 2025-04-08T13:56:21.762Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:7158/session/4dd56b96303baa26e0b7d27d3676ba0a"
[0-11] 2025-04-08T13:56:21.779Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:23073/session/19a17c88e7d477887aef55ce56ea35af"
[0-4] 2025-04-08T13:56:21.868Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:14392/session/e7bd465e0519622eb005f4cc3de3c623"
[0-12] 2025-04-08T13:56:21.877Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:28424/session/71e7a50d74cfc23dea9ba5492b6552c1"
[0-2] 2025-04-08T13:56:21.889Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:2524/session/4c81a8f72688efbf962096e0aa68d07c"
[0-9] 2025-04-08T13:56:21.895Z ERROR webdriver: Could not connect to Bidi protocol of any candidate url in time: "ws://127.0.0.1:18310/session/f92be8d4354f987f85fa00bd23d848f6"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues
