### ISSUE TITLE
Provide a base Dockerfile as a foundation for running tests in a container

### ISSUE THREAD

**Issue by benjaminapetersen** [webdriverio/webdriverio#2618]
## The problem

The world is containerizing, it would be handy to have a base image on [hub.docker.com](hub.docker.com) for `Webdriver.io` that includes everything you need to build a container to run your tests.  This would be helpful as there are [base images for node](https://hub.docker.com/_/node/), [base images for selenium](https://hub.docker.com/u/selenium/), [base images for java](https://hub.docker.com/_/java/), etc, but it is a bit of a hassle to choose one of the base images && then install all the rest of the required packages to get an environment up and running for `webdriver.io` in order to run your tests (and avoid a bit bloated mess! the `nodejs` base image is huge compared to `alpine/node`, for example).  

## Environment

N/A

## Details

N/A

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment]
Great suggestion, I am currently a little bit short on time to take care of this so everyone is welcome to contribute to this.

**Comment by kontrollanten** [comment]
In my current project we're running WebdriverIO in docker containers. We have one container for the application (with webdriverio as dev dep) and another container for Selenium, then we use docker compose to combine those. Is there really a need for a WebdriverIO base image, what would that include? I mean webdriverio, wdio, etc should be dev dependencies for the project. Isn't the hassle about getting the Selenium environment working? I've some experience with Docker, so maybe I can help with this one, but I just want to understand the needs.

Maybe it's good enough to add an example of a `Dockerfile` and `docker-compose.yml` in the documentation?

**Comment by benjaminapetersen** [comment]
Selenium is def the primary hassle, think I agree!

The thought is to put webdriverio/webdriver/selenium in a single container as a base image, then you could `FROM: wedriverbase` & just add your test layer on that and deploy.  For some setups it makes sense to put everything in separate containers like you have, for others, one deployable unit would be handy.  Think "run once, smoke tests" in production. 

Docker compose is good, kubernetes seems to be eating the world as well, so a self-contained base image gives you flexibility to run either way.  

Examples of `Dockerfile` and `docker-compose.yml` seem a great place to start.  Beyond that, an official base on `hub.docker.com` would be handy if it made sense.

**Comment by kontrollanten** [comment]
I see! The selenium images is [based upon Ubuntu](https://github.com/SeleniumHQ/docker-selenium/blob/master/Base/Dockerfile), so it could be convenient way to just create WebdriverIO image based on some of Seleniums containers.

Do you think the base image should use Selenium Standalone or Grid? I've no experience of Grid, is it possible to port an existing setup using Standalone to Grid without any further configuration changes?

**Comment by benjaminapetersen** [comment]
Good Q, I've only used Selenium Standalone as well, no experience with Grid yet.

**Comment by loren138** [comment]
The circle-ci/node images work well for me.  I'm currently using `node:9-stretch-browsers`.  The openjdk image with browsers also works.  That said, it currently has hang issues with v4.11 on our Jenkins server so you may need to pin webdriver to 4.10.2.

**Comment by mcelotti** [comment]
Here's my current docker-compose.yaml, I'm running tests on chrome/firefox with multiple instances: 
```
# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.9.1-actinium
    ports:
      - "4444:4444"
```
